apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "hadoop.fullname" . }}
  labels:
    app: {{ template "hadoop.name" . }}
    chart: {{ template "hadoop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hadoop.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hadoop.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: hdfs-master
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/utility/hadoop/bootstrap.sh"]
          args: ["-d","master"]
          securityContext:
            capabilities:
              add:
                - ALL
          ports:
          - name: ldap-port
            containerPort: 8181
          - name: search-port
            containerPort: 389
          - name: ssh-port
            containerPort: 22
          - name: ssh-port2
            containerPort: 2122
          - name: ssl-ldap
            containerPort: 636
          - name: hdfs1
            containerPort: 50010
          - name: hdfs2
            containerPort: 50020
          - name: hdfs3
            containerPort: 50070
          - name: hdfs4
            containerPort: 50075
          - name: hdfs5
            containerPort: 50090
          - name: hdfs6
            containerPort: 8020
          - name: hdfs7
            containerPort: 9000
          - name: hdfs8
            containerPort: 54310
          - name: hdfs9
            containerPort: 50470
          - name: hdfs10
            containerPort: 50475
          - name: hdfs11
            containerPort: 1006
          - name: hdfs12
            containerPort: 1019
          - name: httpfs
            containerPort: 14000
          - name: mapred1
            containerPort: 10020
          - name: mapred2
            containerPort: 19888
          - name: mapred3
            containerPort: 10033
          - name: mapred4
            containerPort: 54311
          - name: yarn1
            containerPort: 8030
          - name: yarn2
            containerPort: 8031
          - name: yarn3
            containerPort: 8032
          - name: yarn4
            containerPort: 8033
          - name: yarn5
            containerPort: 8040
          - name: yarn6
            containerPort: 8042
          - name: yarn7
            containerPort: 8088
          - name: yarn8
            containerPort: 8025
          - name: yarn9
            containerPort: 8039
          - name: other1
            containerPort: 49707
          - name: sec1
            containerPort: 50490
          - name: data1
            containerPort: 8010
          env:
          - name: LDAP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ldapsecret
                key: password
          - name: KERB_ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: krbsecret
                key: password
          - name: DOMAIN_NAME
            value: default.svc.cloud.uat
          - name: MASTER
            value: hdfs-master
          - name: HADOOP_INSTALL
            value: /usr/local/hadoop
          - name: KEY_PWD
            value: sumit@1234
          - name: ENABLE_HADOOP_SSL
            value: 'true'
          - name: ENABLE_KERBEROS
            value: 'true'
          - name: ENABLE_KUBERNETES
            value: 'true'
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
